# Model aliases for backward compatibility
# These allow using unprefixed class names (User, Creative, etc.)
# while the actual models live in the Collavre engine

Rails.application.config.to_prepare do
  # Core models
  Object.const_set(:User, Collavre::User) unless Object.const_defined?(:User)
  Object.const_set(:Session, Collavre::Session) unless Object.const_defined?(:Session)
  Object.const_set(:Creative, Collavre::Creative) unless Object.const_defined?(:Creative)
  Object.const_set(:Comment, Collavre::Comment) unless Object.const_defined?(:Comment)
  Object.const_set(:CommentReaction, Collavre::CommentReaction) unless Object.const_defined?(:CommentReaction)
  Object.const_set(:CommentReadPointer, Collavre::CommentReadPointer) unless Object.const_defined?(:CommentReadPointer)
  Object.const_set(:CommentPresenceStore, Collavre::CommentPresenceStore) unless Object.const_defined?(:CommentPresenceStore)
  Object.const_set(:CreativeShare, Collavre::CreativeShare) unless Object.const_defined?(:CreativeShare)
  Object.const_set(:CreativeSharesCache, Collavre::CreativeSharesCache) unless Object.const_defined?(:CreativeSharesCache)
  Object.const_set(:CreativeExpandedState, Collavre::CreativeExpandedState) unless Object.const_defined?(:CreativeExpandedState)
  Object.const_set(:CreativeHierarchy, Collavre::CreativeHierarchy) unless Object.const_defined?(:CreativeHierarchy)
  Object.const_set(:Contact, Collavre::Contact) unless Object.const_defined?(:Contact)
  Object.const_set(:Device, Collavre::Device) unless Object.const_defined?(:Device)
  Object.const_set(:Email, Collavre::Email) unless Object.const_defined?(:Email)
  Object.const_set(:InboxItem, Collavre::InboxItem) unless Object.const_defined?(:InboxItem)
  Object.const_set(:Invitation, Collavre::Invitation) unless Object.const_defined?(:Invitation)
  Object.const_set(:Plan, Collavre::Plan) unless Object.const_defined?(:Plan)
  Object.const_set(:Topic, Collavre::Topic) unless Object.const_defined?(:Topic)
  Object.const_set(:Tag, Collavre::Tag) unless Object.const_defined?(:Tag)
  Object.const_set(:Label, Collavre::Label) unless Object.const_defined?(:Label)
  Object.const_set(:ActivityLog, Collavre::ActivityLog) unless Object.const_defined?(:ActivityLog)
  Object.const_set(:CalendarEvent, Collavre::CalendarEvent) unless Object.const_defined?(:CalendarEvent)
  Object.const_set(:SystemSetting, Collavre::SystemSetting) unless Object.const_defined?(:SystemSetting)
  Object.const_set(:UserTheme, Collavre::UserTheme) unless Object.const_defined?(:UserTheme)
  Object.const_set(:Task, Collavre::Task) unless Object.const_defined?(:Task)
  Object.const_set(:TaskAction, Collavre::TaskAction) unless Object.const_defined?(:TaskAction)
  Object.const_set(:McpTool, Collavre::McpTool) unless Object.const_defined?(:McpTool)
  Object.const_set(:GithubAccount, Collavre::GithubAccount) unless Object.const_defined?(:GithubAccount)
  Object.const_set(:GithubRepositoryLink, Collavre::GithubRepositoryLink) unless Object.const_defined?(:GithubRepositoryLink)
  Object.const_set(:NotionAccount, Collavre::NotionAccount) unless Object.const_defined?(:NotionAccount)
  Object.const_set(:NotionPageLink, Collavre::NotionPageLink) unless Object.const_defined?(:NotionPageLink)
  Object.const_set(:NotionBlockLink, Collavre::NotionBlockLink) unless Object.const_defined?(:NotionBlockLink)
  Object.const_set(:WebauthnCredential, Collavre::WebauthnCredential) unless Object.const_defined?(:WebauthnCredential)
end
