require "bundler/setup"
require "bundler/gem_tasks"

APP_RAKEFILE = File.expand_path("test/dummy/Rakefile", __dir__)

desc "Run engine tests"
task :test do
  Dir.glob("test/**/*_test.rb").each { |f| require_relative f }
end

task default: :test
