import "@hotwired/turbo-rails"
import "./controllers"

import "trix"
import "@rails/actiontext"
import "./register_service_worker"
import "./trix_color_picker"

// Creative page modules
import "./creatives/drag_drop"
import "./api/creatives.api"
import "./creatives_expansion"
import "./creatives_import"
import "./creative_row_editor"
import "./creative_row_swipe"
import "./select_mode"
import "./comments"
import "./mention_menu"
import "./mobile_actions"
import "./export_to_markdown"
import "./action_text_attachment_link"
import "./set_plan_modal"
import "./components/creative_tree_row"
import "./github_integration"
